[package]
name = "tiny-gis-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
encoding = "0.2.33"
resvg = "0.41.0"
shapefile = "0.6.0"
